### ISSUE TITLE
mismatch dimension

### ISSUE THREAD

**Issue by aligoglos** [HolmesShuan/OISR-PyTorch#2]
i tried to run RK3/main.py with RK3 pretrained models but below error occurred:

```
D:\Artificial Intelligence\SuperResolution\New folder\RK3>python main.py --test_only --save_results
Making model...
Load the model from weight/x4.pt
Traceback (most recent call last):
  File "D:\Artificial Intelligence\SuperResolution\New folder\RK3\model\edsr.py", line 60, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: The expanded size of the tensor (64) must match the existing size (256) at non-singleton dimension 0.  Target sizes: [64, 3, 3, 3].  Tensor sizes: [256, 3, 3, 3]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    model = model.Model(args, checkpoint)
  File "D:\Artificial Intelligence\SuperResolution\New folder\RK3\model\__init__.py", line 35, in __init__
    cpu=args.cpu
  File "D:\Artificial Intelligence\SuperResolution\New folder\RK3\model\__init__.py", line 109, in load
    if load_from: self.get_model().load_state_dict(load_from, strict=False)
  File "D:\Artificial Intelligence\SuperResolution\New folder\RK3\model\edsr.py", line 66, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named head.0.weight, whose dimensions in the model are torch.Size([64, 3, 3, 3]) and whose dimensions in the checkpoint are torch.Size([256, 3, 3, 3]).
```

**Comment by HolmesShuan** [comment]
Please refer to the [command](https://github.com/HolmesShuan/OISR-PyTorch/blob/cd1992abfb70c0fdffc7c86a128e45be53e903fe/RK3/demo.sh#L35) in `demo.sh`, e.g.,
```bash
python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --data_range 801-900 --scale 4 --test_only --ext bin --dir_data /your/downloaded/data/path --n_resblocks 22 --n_feats 256 --gpu-id 4,5,6,7 --n_GPUs 4 --chop --pre_train ./RK3/x4.pt
```
especially, 
```
--n_resblocks 22 --n_feats 256
```
.

**Comment by aligoglos** [comment]
how can I test Rk3 in my own image?
